CONFIG_ZMK_POINTING=y

# The pinnacle driver also requires this to include sleep code
CONFIG_ZMK_MOUSE=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Uncomment the following line to enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_EPAPER_ON=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=y
CONFIG_NICE_OLED_WIDGET_WPM=y 
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=y
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_BONGO_CAT=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_BONGO_CAT_ONLY_CAPSLOCK=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_BONGO_CAT=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_WINDOWS=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_CUSTOM_X=100
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_CUSTOM_Y=8
CONFIG_NICE_OLED_WIDGET_MODIFIERS_CUSTOM_X=2
CONFIG_NICE_OLED_WIDGET_MODIFIERS_CUSTOM_Y=66



CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Enables RGB functionality (Uncomment lines below to enable.)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

CONFIG_ZMK_BACKLIGHT_AUTO_OFF_USB=n
#CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
#CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60

# disable "Underglow toggling also controls external power" so that OLED can still run with RGB off
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n


# Milliseconds of inactivity before entering idle state	(10 minute)
CONFIG_ZMK_IDLE_TIMEOUT=30000
# Enable deep sleep support	
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# We use this because we need ZMK_PM, PM_DEVICE and ZMK_PM_DEVICE_SUSPEND_RESUME to get proper sleep notifications into the cirque driver
# since we need all that might as well also turn on SOFT_OFF (which implies all these things but adds an optional SOFT_OFF feature)
CONFIG_ZMK_PM_SOFT_OFF=y

